export const TOKENS = {
  INSPECTO_PROCESSOR: Symbol.for("INDIGO_PROCESSOR"),
  FILE_PROVIDER: Symbol.for("FILE_PROVIDER"),
  INDIGO_PROVIDER: Symbol.for("INDIGO_PROVIDER"),
  MOLECULE_CHECKER_PROVIDER: Symbol.for("MOLECULE_CHECKER_PROVIDER"),
} as const;
