export const TOKENS = {
  INSPECTO_PROCESSOR: Symbol.for("INDIGO_PROCESSOR"),
  RULES_PROCESSOR: Symbol.for("RULES_PROCESSOR"),
  FILE_PROVIDER: Symbol.for("FILE_PROVIDER"),
  INDIGO_PROVIDER: Symbol.for("INDIGO_PROVIDER"),
} as const;
