image: node:16 # or any other specific version of Node.js you prefer

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - npm run test
  artifacts:
    when: always
    reports:
      junit: test-results.xml
    paths:
      - test-results.xml

# Optionally, you can add a deploy stage if needed
# deploy:
#   stage: deploy
#   script:
#     - echo "Deploying application..."

# You can also define variables if needed
# variables:
#   NODE_ENV: 'production'