export interface ChemicalInfo {
  name: string;
  isCaseSensitive: boolean;
}

export const FUNCTIONAL_GROUPS: ChemicalInfo[] = [
  { name: "Ac", isCaseSensitive: true },
  { name: "Bn", isCaseSensitive: true },
  { name: "benzyl", isCaseSensitive: false },
  { name: "Boc", isCaseSensitive: true },
  { name: "Bs", isCaseSensitive: true },
  { name: "brosyl", isCaseSensitive: false },
  { name: "Bu", isCaseSensitive: true },
  { name: "Bz", isCaseSensitive: true },
  { name: "benzoyl", isCaseSensitive: false },
  { name: "Cbz", isCaseSensitive: true },
  { name: "Z", isCaseSensitive: true },
  { name: "Cp", isCaseSensitive: true },
  { name: "DMT", isCaseSensitive: true },
  { name: "DMTr", isCaseSensitive: true },
  { name: "Et", isCaseSensitive: true },
  { name: "FMOC", isCaseSensitive: true },
  { name: "iBu", isCaseSensitive: true },
  { name: "Me", isCaseSensitive: true },
  { name: "Mes", isCaseSensitive: true },
  { name: "Ms", isCaseSensitive: true },
  { name: "Ns", isCaseSensitive: true },
  { name: "nosyl", isCaseSensitive: false },
  { name: "OMe", isCaseSensitive: true },
  { name: "Ph", isCaseSensitive: true },
  { name: "phenyl", isCaseSensitive: false },
  { name: "Pr", isCaseSensitive: true },
  { name: "sBu", isCaseSensitive: true },
  { name: "SEM", isCaseSensitive: true },
  { name: "TBDMS", isCaseSensitive: true },
  { name: "TBDPS", isCaseSensitive: true },
  { name: "Tf", isCaseSensitive: true },
  { name: "TIPS", isCaseSensitive: true },
  { name: "TMS", isCaseSensitive: true },
  { name: "Ts", isCaseSensitive: true },
  { name: "tosyl", isCaseSensitive: false },
];

export const SOLVENTS: ChemicalInfo[] = [
  { name: "DCE", isCaseSensitive: true },
  { name: "EDC", isCaseSensitive: true },
  { name: "1,2-dimethoxyethane", isCaseSensitive: false },
  { name: "DME", isCaseSensitive: true },
  { name: "1,4-dioxane", isCaseSensitive: false },
  { name: "2-methoxyethanol", isCaseSensitive: false },
  { name: "acetic acid", isCaseSensitive: false },
  { name: "acetonitrile", isCaseSensitive: false },
  { name: "benzene", isCaseSensitive: false },
  { name: "chloroform", isCaseSensitive: false },
  { name: "cyclohexanol", isCaseSensitive: false },
  { name: "diglyme", isCaseSensitive: false },
  { name: "dimethyl carbonate", isCaseSensitive: false },
  { name: "DMF", isCaseSensitive: true },
  { name: "DMSO", isCaseSensitive: true },
  { name: "Ethyl alcohol", isCaseSensitive: false },
  { name: "EtOH", isCaseSensitive: true },
  { name: "ethyl acetate", isCaseSensitive: false },
  { name: "ethane-1,2-diol", isCaseSensitive: false },
  { name: "formamide", isCaseSensitive: false },
  { name: "formic acid", isCaseSensitive: false },
  { name: "glycerol", isCaseSensitive: false },
  { name: "n-heptane", isCaseSensitive: false },
  { name: "n-Hexane", isCaseSensitive: false },
  { name: "isooctane", isCaseSensitive: false },
  { name: "methyl acetate", isCaseSensitive: false },
  { name: "methyl formate", isCaseSensitive: false },
  { name: "MTBE", isCaseSensitive: true },
  { name: "Methyl t-butyl ether", isCaseSensitive: false },
  { name: "nitromethane", isCaseSensitive: false },
  { name: "NMP", isCaseSensitive: true },
  { name: "n-pentane", isCaseSensitive: false },
  { name: "propylene carbonate", isCaseSensitive: false },
  { name: "sulfolane", isCaseSensitive: false },
  { name: "THF", isCaseSensitive: true },
  { name: "Toluene", isCaseSensitive: false },
  { name: "Water", isCaseSensitive: false },
];

export const SOLVENT_LIST: Record<string, string[]> = {
  "acetic acid": ["ethanoic acid", "ethylic acid", "methane carboxylic acid"],
  acetone: ["2-propanone", "dimethyl ketone", "propanone"],
  acetonitrile: ["methyl cyanide"],
  benzene: ["benzol"],
  "1-butanol": ["n-butanol"],
  "2-butanol": ["butan-2-ol"],
  "2-butanone": ["methyl ethyl ketone", "MEK"],
  "t-butyl alcohol": ["tert-butyl alcohol"],
  "carbon tetrachloride": ["benzinoform"],
  chlorobenzene: ["phenyl chloride"],
  chloroform: ["trichloromethane"],
  cyclohexane: ["Hexanaphthene (archaic)"],
  "1,2-dichloroethane": ["DCE"],
  "diethylene glycol": ["2,2′-oxydiethanol"],
  "diethyl ether": ["ether"],
  diglyme: ["diethylene glycol dimethyl ether"],
  "dimethyl ether": ["1,2-dimethoxyethane", "glyme", "DME"],
  dimethylformamide: ["DMF"],
  "dimethyl sulfoxide": ["DMSO"],
  "1,4-dioxane": ["diethylene dioxide"],
  ethanol: ["ethyl alcohol", "EtOH"],
  "ethyl acetate": ["acetic ester", "acetic ether", "ethyl ethanoate"],
  "ethylene glycol": ["ethane-1,2-diol"],
  glycerin: ["glycerol", "glucerite"],
  heptane: ["n-heptane"],
  hexamethylphosphoramide: ["HMPA"],
  hexane: ["n-hexane"],
  methanol: ["methyl alcohol"],
  "methyl t-butyl ether": ["MTBE"],
  "N-methyl-2-pyrrolidinone": ["NMP"],
  nitromethane: ["nitrocarbol"],
  pentane: ["amylene"],
  "petroleum ether": ["ligroine"],
  "1-propanol": ["n-propyl alcohol"],
  "2-propanol": ["isopropanol", "dimethyl carbinol"],
  pyridine: ["azine"],
  tetrahydrofuran: ["THF"],
  toluene: ["toluol"],
  triethylamine: ["diethylaminoethane"],
  water: ["H2O"],
  "heavy water": ["D2O"],
  "o-xylene": ["1,2-dimethylbenzene", "orthoxylene"],
  "m-xylene": ["1,3-dimethylbenzene", "metaxylene"],
  "p-xylene": ["1,4-dimethylbenzene", "paraxylene"],
};
