name: Sonar Scan
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: "20.1.0"

      - name: Install dependencies
        run: pnpm install
      - name: Run tests and collect coverage
        run: pnpm run test:coverage
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
