name: InspectoTestsCheck

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  vitest:
    name: Vitest
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: "20.1.0"

      - name: Install dependencies
        run: pnpm install

      - name: RUN
        run: pnpm run test
